version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: ruby -v
          command: ruby -v

jobs:
  slack-notification:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: exit 0
      - slack/status

orbs:
  slack: circleci/slack@3.4.2
version: 2.1
workflows:
  my-workflow:
    jobs:
      - slack-notification
